version: '3'

services:
   db:
      image: postgres:latest
      restart: always
      environment:
         POSTGRES_PASSWORD: dev
         POSTGRES_USER: dev
         POSTGRES_DB: shard
      ports:
         - 5432:5432
